spring.application.name=Ntm

spring.datasource.url=jdbc:mysql://localhost:3306/ntm_db (o algo así)
spring.datasource.username=root
spring.datasource.password=agregar_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true